//! Token definitions compiled from `def/lexer/tokens/*.lfy`.
//!
//! Every `enum` in the source becomes a Rust enum generated by [`token_enum!`], which
//! keeps the original key, the matched source text (`value`) and the definition text.

pub mod comment;
pub mod identifier;
pub mod keyword;
pub mod literal;
pub mod operator;
pub mod separator;
pub mod traits;
pub mod whitespace;

/// Generates a token enum with `ALL`, `key()`, `value()`, `definition()`, `from_value()`
/// and `matches_at()` from a list of `Variant => (KEY, value, definition)` entries.
macro_rules! token_enum {
    (
        $(#[$meta:meta])*
        $vis:vis enum $name:ident {
            $( $variant:ident => ($key:literal, $value:literal, $definition:literal) ),+ $(,)?
        }
    ) => {
        $(#[$meta])*
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        $vis enum $name {
            $( $variant ),+
        }

        impl $name {
            /// Every member, in declaration order.
            pub const ALL: &'static [$name] = &[ $( $name::$variant ),+ ];

            /// The member's key in the source definition.
            pub fn key(self) -> &'static str {
                match self { $( $name::$variant => $key ),+ }
            }

            /// The source text this member matches.
            pub fn value(self) -> &'static str {
                match self { $( $name::$variant => $value ),+ }
            }

            /// The member's definition (`key@definition`).
            pub fn definition(self) -> &'static str {
                match self { $( $name::$variant => $definition ),+ }
            }

            /// The member whose value is exactly `value`, if any.
            pub fn from_value(value: &str) -> Option<Self> {
                Self::ALL.iter().copied().find(|member| member.value() == value)
            }

            /// Every member whose value is a prefix of `rest`, with the matched byte length.
            pub fn matches_at(rest: &str) -> impl Iterator<Item = (Self, usize)> + '_ {
                Self::ALL
                    .iter()
                    .copied()
                    .filter(move |member| rest.starts_with(member.value()))
                    .map(|member| (member, member.value().len()))
            }
        }
    };
}

pub(crate) use token_enum;
